# Generated by Django 2.2 on 2020-07-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
