# Generated by Django 2.2 on 2020-07-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=True, upload_to='profile', verbose_name='الصوره الشخصية'),
            preserve_default=False,
        ),
    ]
