# Generated by Django 2.2 on 2020-07-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200731_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Specialist_doctor',
            field=models.CharField(choices=[('عظام', 'عظام'), ('باطنة', 'باطنه'), ('نسا وتوليد', 'نسا وتوليد'), ('جراحه تجميل', 'جراحه تجميل'), ('تخسيس', 'تخسيس'), ('اطفال', 'اطفال'), ('انف واذن', 'انف واذن'), ('امراض دم', 'امراض دم'), ('جراحه عامه', 'جراحه عامه'), ('حميات', 'حميات'), ('جراحه اطفال', 'جراحه اططفال'), ('مخ واعصاب', 'مخ واعصاب'), ('اورام', 'اورام'), ('اسنان', 'اسنان')], default='باطنه', max_length=255, verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Waiting_time',
            field=models.IntegerField(default=1, verbose_name='مدة الانتظار'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان بالتفصيل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.IntegerField(default=1, verbose_name='ساعات العمل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم'),
        ),
    ]
