# Generated by Django 2.2 on 2020-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200801_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'التعليق', 'verbose_name_plural': 'التعليقات'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='Specialist_doctor',
            field=models.CharField(choices=[('جراحه اطفال', 'جراحه اططفال'), ('تخسيس', 'تخسيس'), ('اطفال', 'اطفال'), ('مخ واعصاب', 'مخ واعصاب'), ('عظام', 'عظام'), ('انف واذن', 'انف واذن'), ('جراحه تجميل', 'جراحه تجميل'), ('امراض دم', 'امراض دم'), ('اسنان', 'اسنان'), ('باطنة', 'باطنه'), ('جراحه عامه', 'جراحه عامه'), ('حميات', 'حميات'), ('اورام', 'اورام'), ('نسا وتوليد', 'نسا وتوليد')], default='باطنه', max_length=255, verbose_name='التخصص'),
        ),
    ]
