# Generated by Django 2.2 on 2020-08-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200801_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Specialist_doctor',
            field=models.CharField(choices=[('عظام', 'عظام'), ('نسا وتوليد', 'نسا وتوليد'), ('اسنان', 'اسنان'), ('باطنة', 'باطنه'), ('جراحه عامه', 'جراحه عامه'), ('جراحه تجميل', 'جراحه تجميل'), ('اورام', 'اورام'), ('حميات', 'حميات'), ('مخ واعصاب', 'مخ واعصاب'), ('تخسيس', 'تخسيس'), ('امراض دم', 'امراض دم'), ('اطفال', 'اطفال'), ('انف واذن', 'انف واذن'), ('جراحه اطفال', 'جراحه اططفال')], default='باطنه', max_length=255, verbose_name='التخصص'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=11, verbose_name='رقم الهاتف')),
                ('age', models.IntegerField(verbose_name='السن')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
