# Generated by Django 2.2 on 2020-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200801_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'الحجز', 'verbose_name_plural': 'الحجوزات'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='Specialist_doctor',
            field=models.CharField(choices=[('نسا وتوليد', 'نسا وتوليد'), ('جراحه تجميل', 'جراحه تجميل'), ('امراض دم', 'امراض دم'), ('حميات', 'حميات'), ('عظام', 'عظام'), ('انف واذن', 'انف واذن'), ('تخسيس', 'تخسيس'), ('اورام', 'اورام'), ('جراحه اطفال', 'جراحه اططفال'), ('جراحه عامه', 'جراحه عامه'), ('اسنان', 'اسنان'), ('اطفال', 'اطفال'), ('باطنة', 'باطنه'), ('مخ واعصاب', 'مخ واعصاب')], default='باطنه', max_length=255, verbose_name='التخصص'),
        ),
    ]
