# Generated by Django 2.2 on 2020-08-02 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_auto_20200802_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Specialist_doctor',
            field=models.CharField(choices=[('نسا وتوليد', 'نسا وتوليد'), ('حميات', 'حميات'), ('اطفال', 'اطفال'), ('انف واذن', 'انف واذن'), ('جراحه اطفال', 'جراحه اططفال'), ('امراض دم', 'امراض دم'), ('اسنان', 'اسنان'), ('تخسيس', 'تخسيس'), ('عظام', 'عظام'), ('اورام', 'اورام'), ('باطنة', 'باطنه'), ('جراحه تجميل', 'جراحه تجميل'), ('مخ واعصاب', 'مخ واعصاب'), ('جراحه عامه', 'جراحه عامه')], default='باطنه', max_length=255, verbose_name='التخصص'),
        ),
    ]
